name: Build intrinsic_sdk_cmake container images
run-name: ${{ github.actor }}'s changes have triggered a build of the sdk container images.
on:
  workflow_call:
    outputs:
      intrinsic_ai_sdk_version:
        description: "The intrinsic-ai/sdk version being used"
        value: ${{ jobs.build-container-images.outputs.intrinsic_ai_sdk_version }}
jobs:
  build-container-images:
    runs-on: ubuntu-26.04-8core
    services:
      # This local container registry is used to temporarily hold intermediate
      # docker images until they can be tested without pushing to the remote
      # container registry on ghcr.io.
      registry:
        image: registry:3
        ports:
          - 5000:5000
    outputs:
      intrinsic_ai_sdk_version: ${{ steps.intrinsic_ai_sdk_version.outputs.version }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Checkout.
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # was: actions/checkout@v4.2.2

      # Extract the intrinsic sdk version being used.
      - name: Get intrinsic-ai/sdk Version
        run: echo "INTRINSIC_AI_SDK_VERSION=$(cat intrinsic_sdk_bundle_library_py/resource/sdk_version.json | jq -r '.sdk_version')" >> $GITHUB_ENV
      - run: |
          if [ -z "$INTRINSIC_AI_SDK_VERSION" ]; then
            echo "Error: INTRINSIC_AI_SDK_VERSION is empty!" >&2
            exit 1
          fi
      - run: echo "The Intrinsic SDK version being used is ${{ env.INTRINSIC_AI_SDK_VERSION }}"
      - id: intrinsic_ai_sdk_version
        run: echo "version=${{ env.INTRINSIC_AI_SDK_VERSION }}" >> "$GITHUB_OUTPUT"

      # Set up buildx.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # was: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # was: docker/setup-buildx-action@v3
        id: setup-buildx
        with:
          # This is needed in order to let buildx push to the local repository.
          driver-opts: network=host

      # Set up the GitHub Action Caches where we'll store the docker cache-mount volumes.
      - name: GitHub Action Cache for var-cache-apt
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-var-cache-apt
        with:
          path: var-cache-apt
          key: buildx-cache-mount-for-var-cache-apt-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-var-cache-apt-${{ runner.os }}
      - name: GitHub Action Cache for var-lib-apt
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-var-lib-apt
        with:
          path: var-lib-apt
          key: buildx-cache-mount-for-var-lib-apt-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-var-lib-apt-${{ runner.os }}
      - name: GitHub Action Cache for ccache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-ccache
        with:
          path: ccache
          key: buildx-cache-mount-for-ccache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-ccache-${{ runner.os }}

      # Set up the caching of docker cache-mount volumes which normally live
      # inside a .db file that the buildx container keeps.
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@5b81f4d29dc8397a7d341dba3aeecc7ec54d6361 # was: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "ccache": "/ccache"
            }

      # Build the base, normal, and run images.
      # They are tagged and pushed into the local container registry service so
      # subsequent images can use them to build, and they are output to tar
      # files so they can be uploaded as artifacts at the end.
      - name: Build intrinsic_sdk_cmake_base Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: .
          file: intrinsic_sdk_cmake/docker_images/intrinsic_sdk_cmake_base.Dockerfile
          push: true
          # TODO(wjwwood): The cache for gha (GitHub Actions) is limited,
          # consider trying the registry cache type that caches to an image, see:
          # https://www.blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
          outputs: type=docker,dest=${{ runner.temp }}/intrinsic_sdk_cmake_base.tar
          tags: |
            localhost:5000/intrinsic_sdk_cmake_base:temp
      - name: Build intrinsic_sdk_cmake Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: .
          file: intrinsic_sdk_cmake/docker_images/intrinsic_sdk_cmake.Dockerfile
          push: true
          outputs: type=docker,dest=${{ runner.temp }}/intrinsic_sdk_cmake.tar
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            BASE_IMAGE_TAG=temp
          tags: |
            localhost:5000/intrinsic_sdk_cmake:temp
      - name: Build intrinsic_sdk_cmake_run Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: .
          file: intrinsic_sdk_cmake/docker_images/intrinsic_sdk_cmake_run.Dockerfile
          # No push for the last one since there is no subsequent image that needs it.
          # push: true
          outputs: type=docker,dest=${{ runner.temp }}/intrinsic_sdk_cmake_run.tar
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            BASE_IMAGE_TAG=temp
          tags: |
            localhost:5000/intrinsic_sdk_cmake_run:temp

      # Upload images as temporary build artifacts for use in other jobs.
      - name: Upload intrinsic_sdk_cmake_base image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # was: actions/upload-artifact@v4
        with:
          name: intrinsic_sdk_cmake_base_image
          path: ${{ runner.temp }}/intrinsic_sdk_cmake_base.tar
          retention-days: "1"
      - name: Upload intrinsic_sdk_cmake image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # was: actions/upload-artifact@v4
        with:
          name: intrinsic_sdk_cmake_image
          path: ${{ runner.temp }}/intrinsic_sdk_cmake.tar
          retention-days: "1"
      - name: Upload intrinsic_sdk_cmake_run image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # was: actions/upload-artifact@v4
        with:
          name: intrinsic_sdk_cmake_run_image
          path: ${{ runner.temp }}/intrinsic_sdk_cmake_run.tar
          retention-days: "1"

      - run: echo "🍏 This job's status is ${{ job.status }}."
