name: Build and Test Container Images
run-name: ${{ github.actor }}'s changes have triggered a build, test, and push of the sdk container images.
on:
  workflow_call:
    outputs:
      intrinsic_ai_sdk_version:
        description: "The intrinsic-ai/sdk version being used"
        value: ${{ jobs.test-container-images.outputs.intrinsic_ai_sdk_version }}
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  build-container-images:
    uses: ./.github/workflows/build_container_images.yaml
  test-container-images:
    runs-on: ubuntu-26.04-8core
    needs: [build-container-images]
    outputs:
      intrinsic_ai_sdk_version: ${{ needs.build-container-images.outputs.intrinsic_ai_sdk_version }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Checkout.
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # was: actions/checkout@v4.2.2

      # Extract the intrinsic sdk version being used.
      - name: Get intrinsic-ai/sdk Version
        run: echo "INTRINSIC_AI_SDK_VERSION=${{ needs.build-container-images.outputs.intrinsic_ai_sdk_version }}" >> $GITHUB_ENV
      - run: echo "The Intrinsic SDK version being used is ${{ env.INTRINSIC_AI_SDK_VERSION }}"

      # Download images from build workflow and load them into the local docker for testing.
      - name: Download intrinsic_sdk_cmake_base container image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # was: actions/download-artifact@v4
        with:
          name: intrinsic_sdk_cmake_base_image
          path: ${{ runner.temp }}
      - name: Load intrinsic_sdk_cmake_base container image into docker
        run: docker load --input ${{ runner.temp }}/intrinsic_sdk_cmake_base.tar
      - name: Download intrinsic_sdk_cmake container image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # was: actions/download-artifact@v4
        with:
          name: intrinsic_sdk_cmake_image
          path: ${{ runner.temp }}
      - name: Load intrinsic_sdk_cmake container image into docker
        run: docker load --input ${{ runner.temp }}/intrinsic_sdk_cmake.tar
      - name: Download intrinsic_sdk_cmake_run container image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # was: actions/download-artifact@v4
        with:
          name: intrinsic_sdk_cmake_run_image
          path: ${{ runner.temp }}
      - name: Load intrinsic_sdk_cmake_run container image into docker
        run: docker load --input ${{ runner.temp }}/intrinsic_sdk_cmake_run.tar

      # Set up the GitHub Action Caches to use the cached docker cache-mount volumes.
      - name: GitHub Action Cache for var-cache-apt
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-var-cache-apt
        with:
          path: var-cache-apt
          key: buildx-cache-mount-for-var-cache-apt-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-var-cache-apt-${{ runner.os }}
      - name: GitHub Action Cache for var-lib-apt
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-var-lib-apt
        with:
          path: var-lib-apt
          key: buildx-cache-mount-for-var-lib-apt-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-var-lib-apt-${{ runner.os }}
      - name: GitHub Action Cache for ccache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was: actions/cache@v4
        id: cache-for-ccache
        with:
          path: ccache
          key: buildx-cache-mount-for-ccache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            buildx-cache-mount-for-ccache-${{ runner.os }}

      # Set up the caching of docker cache-mount volumes which normally live
      # inside a .db file that the buildx container keeps.
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@5b81f4d29dc8397a7d341dba3aeecc7ec54d6361 # was: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "ccache": "/ccache"
            }

      # Build the test case using the temporary images.
      - name: Test intrinsic_sdk_cmake Docker Images
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: intrinsic_sdk_cmake
          file: intrinsic_sdk_bundle_library_py/resource/skill.Dockerfile
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            SKILL_NAME=test_cpp_skill
            SKILL_PACKAGE=intrinsic_sdk_cmake
            SKILL_EXECUTABLE=lib/intrinsic_sdk_cmake/test_cpp_skill_main
            SKILL_CONFIG=share/intrinsic_sdk_cmake/test_cpp_skill_config.pbbin
          tags: |
            test_intrinsic_sdk_cmake_images:temp

      - name: Test test_python_skill Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: intrinsic_sdk_bundle_library_py/test/functional_tests/test_python_skill
          file: intrinsic_sdk_bundle_library_py/resource/skill.Dockerfile
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            SKILL_NAME=test_python_skill
            SKILL_PACKAGE=test_python_skill
            SKILL_TYPE=python
            SKILL_EXECUTABLE=lib/test_python_skill/test_python_skill_main
            SKILL_CONFIG=share/test_python_skill/test_python_skill_config.pbbin
          tags: |
            test_python_skill:temp

      - name: Test test_python_service Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: .
          file: intrinsic_sdk_bundle_library_py/resource/service.Dockerfile
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            SERVICE_NAME=test_python_service
            SERVICE_PACKAGE=test_python_service
            SOURCE_DIR=.
            OVERLAY_SOURCE=intrinsic_sdk_bundle_library_py/test/functional_tests/test_python_service
          tags: |
            test_python_service:temp

      - name: Test test_cpp_skill Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: intrinsic_sdk_bundle_library_py/test/functional_tests/test_cpp_skill
          file: intrinsic_sdk_bundle_library_py/resource/skill.Dockerfile
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            SKILL_NAME=test_cpp_skill
            SKILL_PACKAGE=test_cpp_skill
            SKILL_TYPE=cpp
            SKILL_EXECUTABLE=lib/test_cpp_skill/test_cpp_skill_main
            SKILL_CONFIG=share/test_cpp_skill/test_cpp_skill_config.pbbin
          tags: |
            test_cpp_skill:temp

      - name: Test test_cpp_service Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # was: docker/build-push-action@v5
        with:
          context: .
          file: intrinsic_sdk_bundle_library_py/resource/service.Dockerfile
          build-args: |
            REPOSITORY=localhost:5000
            TAG=temp
            SERVICE_NAME=test_cpp_service
            SERVICE_PACKAGE=test_cpp_service
            SOURCE_DIR=.
            OVERLAY_SOURCE=intrinsic_sdk_bundle_library_py/test/functional_tests/test_cpp_service
          tags: |
            test_cpp_service:temp

      - run: echo "🍏 This job's status is ${{ job.status }}."
